#################### For Alpine Distribution ####################

# FROM alpine:3.7
# RUN apk add --no-cache mysql-client
# ENTRYPOINT ["mysql"]
# This example has a virtual image size of only 36.8MB. Compare that to our good friend Ubuntu:


FROM alpine:3.7

# add workspace location for typescript code

# run npm install

# run tsc command

# add port to run docker container from on browser

#################### For Alpine Distribution ####################


#################### For Ubuntu Distribution ####################

# FROM ubuntu:18.04
# RUN apt-get update \
#     && apt-get install -y --no-install-recommends mysql-client \
#     && rm -rf /var/lib/apt/lists/*
# ENTRYPOINT ["mysql"]

#################### For Ubuntu Distribution ####################